Up

diff --git a/.initial/initial b/.initial/initial
--- a/.initial/initial
+++ b/.initial/initial
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+export DEBIAN_FRONTEND="noninteractive"
+
+# Add password to default user
+sudo passwd ubuntu
+
 # Link dotfiles
 ln -sfv "$HOME/.dotfiles/.vim" ~
 ln -sfv "$HOME/.dotfiles/.bin" ~
@@ -37,6 +42,8 @@ sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y \
     whois \
     protobuf-compiler \
     apt-transport-https \
+    shellcheck \
+    visidata \
     silversearcher-ag
 
 # Change default shell to ZSH for user and root
@@ -47,5 +54,55 @@ sudo chsh -s /usr/bin/zsh
 sudo ufw allow ssh
 sudo ufw enable
 
-# Change Date & Time
-sudo dpkg-reconfigure tzdata
+# Sets Timezone to EU/Berlin
+export TZ='Europe/Berlin'
+ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime && sudo dpkg-reconfigure tzdata
+
+# Create host key
+cd $HOME
+ssh-keygen -t rsa \
+    -b 4096 \
+    -f ssh_host_key \
+    -C '' \
+    -N ''
+
+# Configure SSH
+sudo mv $HOME/ssh_host_key $HOME/ssh_host_key.pub /etc/ssh/
+sudo chown root:root /etc/ssh/ssh_host_key /etc/ssh/ssh_host_key.pub
+sudo chmod 0600 /etc/ssh/ssh_host_key
+sudo cp ~/.dotfiles/.config/sshd_config /etc/ssh/
+
+sudo service ssh restart
+
+ssh-keygen -E sha256 -lf /etc/ssh/ssh_host_key.pub
+
+# Install fzf
+git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
+$HOME/.fzf/install
+
+# Build TMUX from source
+git clone --depth=1 https://github.com/tmux/tmux.git $HOME/tmux
+cd $HOME/tmux || return
+sh autogen.sh
+./configure
+make
+sudo make install
+cd ..
+rm -rf $HOME/tmux
+
+# Build VIM from source
+git clone --depth=1 https://github.com/vim/vim.git $HOME/vim
+cd $HOME/vim || return
+./configure \
+    --with-features=huge \
+    --enable-multibyte \
+    --enable-python3interp=yes
+    make
+sudo make install
+cd && sudo rm -rfv $HOME/vim
+
+# Cleanup bash files
+rm -rf $HOME/.bashrc
+rm -rf $HOME/.bash_history
+rm -rf $HOME/.bash_logout
+rm -rf $HOME/.profile
